from heap import Heap
import random
import time

def test1():
    print("-------------Test 1-------------")
    landing_queue = Heap()
    landing_queue.add(4, 'Flight 337')
    landing_queue.add(2, 'Flight 4189')
    landing_queue.add(5, 'Flight 8675')
    landing_queue.add(3, 'Flight 309')
    print(str(landing_queue.max()))
    landing_queue.add(8, 'Flight Amy Heart')
    landing_queue.add(3, 'Flight San Diego')
    print(str(landing_queue.max()))
    landing_queue.remove_max()
    print(str(landing_queue.max()))

def test2():
    print("-------------Test 2-------------")
    landing_queue = Heap()
    landing_queue.add(20, 'Flight Karloman')
    landing_queue.remove_max()
    landing_queue.add(92, 'Flight Queen Elizabeth')
    landing_queue.add(32, 'Flight Alexander')
    landing_queue.remove_max()
    landing_queue.add(82, 'Flight Hawking')
    landing_queue.remove_max()
    landing_queue.add(67, 'Flight Washington')
    landing_queue.add(41, 'Flight Lionheart')
    landing_queue.remove_max()
    landing_queue.add(59, 'Flight William')
    landing_queue.remove_max()
    landing_queue.add(81, 'Flight Victoria')
    landing_queue.remove_max()
    landing_queue.remove_max()
    landing_queue.add(71, 'Flight Suleiman')
    landing_queue.add(78, 'Flight Ghandi')
    landing_queue.remove_max()
    print(str(landing_queue.max()))
    landing_queue.remove_max()
    landing_queue.remove_max()
    print(landing_queue.is_empty())
    landing_queue.remove_max()

def test3():
    print("-------------Test 3-------------")
    landing_queue = Heap()
    landing_queue.add(2, 'Flight 2008')
    landing_queue.add(2, 'Flight 815')
    landing_queue.add(3, 'Flight 512')
    landing_queue.remove_max()
    print(str(landing_queue.max()))
    landing_queue.add(11, 'Flight Year 98')
    landing_queue.add(2, 'Flight Great Chocolate')
    landing_queue.remove_max()
    landing_queue.add(6, 'Flight 19')
    landing_queue.add(15, 'Flight Class 2020')
    landing_queue.add(4, 'Flight 331')
    landing_queue.remove_max()
    landing_queue.remove_max()
    print(str(landing_queue.max()))
    landing_queue.add(7, 'Flight Great Escape')
    landing_queue.add(15, 'Flight Great Days')
    landing_queue.remove_max()
    landing_queue.remove_max()
    print(landing_queue)

def test4():
    print("-------------Test 4-------------")
    landing_queue = Heap()
    landing_queue.add(1, "Flight Late")
    landing_queue.add(11, "Flight Star")
    landing_queue.remove_max()
    landing_queue.add(12, "Flight Pistons")
    landing_queue.remove_max()
    landing_queue.add(11, "Flight Lions")
    landing_queue.remove_max()
    landing_queue.add(13, "Flight Spartans")
    landing_queue.remove_max()
    landing_queue.add(14, "Flight Jaguars")
    landing_queue.remove_max()
    landing_queue.add(20, "Flight Tigers")
    landing_queue.remove_max()
    landing_queue.add(10, "Flight Bengals")
    landing_queue.add(5, "Flight Shocks")
    landing_queue.add(16, "Flight Leprechauns")
    landing_queue.remove_max()
    landing_queue.add(13, "Flight Sheep")
    landing_queue.remove_max()
    landing_queue.add(14, "Flight Dragons")
    landing_queue.remove_max()
    landing_queue.add(20, "Flight Birds")
    landing_queue.remove_max()
    print(landing_queue)
def test5():
    print("-------------Test 5-------------")
    landing_queue = Heap()
    random.seed(10)
    for i in range(100):
        k = random.randint(0, 100)
        v = str(k) + str(i)
        if k%2 == 0:
            landing_queue.add(k,v)
        else:
            landing_queue.remove_max()
    print(landing_queue)




def main():
    test1()
    test2()
    test3()
    test4()
    test5()


main()